version: '3.8'

services:
  maid:
    image: gaodes/maid:latest
    container_name: maid-service
    restart: always
    volumes:
      # Mount a directory of rules
      - ./rules:/root/.maid/rules
      # Mount logs directory
      - ${HOME}/.maid/logs:/root/.maid/logs
      # Optional: Mount the directories you want to clean
      # - /path/to/clean:/path/to/clean
    # The container will run in the background with tail -f /dev/null